services:
  # База данных
  postgres:
    image: postgres:15
    container_name: clinic-postgres
    environment:
      POSTGRES_DB: clinic_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - clinic-network

  # Eureka Discovery Server
  discovery-service:
    build:
      context: ./discovery-service
      dockerfile: Dockerfile
    container_name: discovery-service
    ports:
      - "8761:8761"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    networks:
      - clinic-network
    depends_on:
      - postgres

  # API Gateway
  gateway-service:
    build:
      context: ./gateway-service
      dockerfile: Dockerfile
    container_name: gateway-service
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery-service:8761/eureka
    networks:
      - clinic-network
    depends_on:
      - discovery-service

  # Микросервисы
  staff-service:
    build:
      context: ./staff-service
      dockerfile: Dockerfile
    container_name: staff-service
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery-service:8761/eureka
    networks:
      - clinic-network
    depends_on:
      - discovery-service
      - postgres

  patient-service:
    build:
      context: ./patient-service
      dockerfile: Dockerfile
    container_name: patient-service
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery-service:8761/eureka
    networks:
      - clinic-network
    depends_on:
      - discovery-service
      - postgres

  appointment-service:
    build:
      context: ./appointment-service
      dockerfile: Dockerfile
    container_name: appointment-service
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery-service:8761/eureka
    networks:
      - clinic-network
    depends_on:
      - discovery-service
      - postgres

  audit-service:
    build:
      context: ./audit-service
      dockerfile: Dockerfile
    container_name: audit-service
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery-service:8761/eureka
    networks:
      - clinic-network
    depends_on:
      - discovery-service
      - postgres

  export-service:
    build:
      context: ./export-service
      dockerfile: Dockerfile
    container_name: export-service
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery-service:8761/eureka
    networks:
      - clinic-network
    depends_on:
      - discovery-service
      - postgres

volumes:
  postgres_data:

networks:
  clinic-network:
    driver: bridge